#!/usr/bin/env python3
# -*- coding=utf-8 -*-
r"""

"""
import sys
import fileinput


def main():
    with fileinput.input(()) as f:
        for i, line in enumerate(f):
            sys.stdout.write(f"{i:<2} {line}")
    return 0


if __name__ == '__main__':
    sys.exit(main() or 0)
