#!/usr/bin/env bash
################################################################################
# Serves a folder in http-mode with support to set the baseurl.                #
# Modify the $SOURCE, $BASEURL or $PORT to your needs.                         #
# ---------------------------------------------------------------------------- #
# This file was taken from the utilities-sh project:                           #
# https://github.com/utility-libraries/utilities-sh/tree/main/http-serve       #
################################################################################
set -e  # fail on any error

# supposed the shell-script in a scripts/ folder or so.
# if the script is in the root directory remove the ../ at the end
ROOT="$(realpath "$(dirname "$(realpath "$0")")/../")"
cd "$ROOT"

################################## Modifiable ##################################
# Source folder to serve
SOURCE=docs/
# baseurl which should be used
BASEURL=
# Port to serve on
PORT=${PORT:-8000}
################################################################################

SOURCE=$(realpath "${SOURCE}")  # make absolute in case we change the CWD
BASEURL="${BASEURL#/}"  # remove prefix / if available

if [ ! -d "$SOURCE" ]; then
  echo "Source folder does not exist (${SOURCE})"
  exit 1
fi

IFS=" " read -r -a IPS <<< "$(hostname -I)"  # somehow read network-ip
HOST="${IPS[0]}"  # first found network-ip

if [ -z "$BASEURL" ]; then  # no BASEURL. go directly into the source directory
  cd "$SOURCE"
else  # BASEURL set. simulate it with directories
  # creates a tempdir with a folder structure similar to the baseurl as pythons http.server serves the current folder as is
  TMPDIR=$(mktemp --directory)  # create temporary directory to serve
  cd "${TMPDIR}"  # go into the TMP-Directory
  mkdir -p "$(dirname "${BASEURL}")"  # create first parts of BASEURL (eg "/web/docs/" creates web/)
  ln -s "${SOURCE}" "${BASEURL%/}"  # link final part to the source directory
  trap 'rm -rf -- "${TMPDIR}"' EXIT  # remove TMPDIR at exit

  # index file to redirect to the baseurl
  echo "<!DOCTYPE html>
  <html lang=\"en\">
  <head>
      <title>redirecting...</title>
      <meta http-equiv=\"Refresh\" content=\"0; url='/${BASEURL}'\">
  </head>
  <body style=\"display: grid; place-content: center; min-height: 100vh; font-size: 4vw; text-align: center;\">
      <p>If you see this page the automatic redirect did not work. Please click the link below</p>
      <a href=\"/${BASEURL}\">/${BASEURL}</a>
  </body>
  </html>" > "${TMPDIR}/index.html"
fi

echo "Serving documentation on http://${HOST}:${PORT}/${BASEURL}"
python3 -m http.server --bind 0.0.0.0 "$PORT" > /dev/null
